### ISSUE TITLE
Deprecate String into appTester function?

### ISSUE THREAD

**Issue by bryanhelmig** [zapier/zapier-platform-core#1]
I've been using what I think is a much less magical way to test methods:

```javascript
const App = require('../index');
const appTester = zapier.createAppTester(App);

// prefer:
appTester(App.authentication.test);
// instead of:
appTester('authentication.test');

// prefer:
appTester(App.resources.member.list.operation.perform);
// instead of:
appTester('member.list');
```

Thoughts @bcooksey? 

> Moved from https://github.com/zapier/zapier-platform-cli/issues/2.

**Comment by bcooksey** [comment]
Yes please! I always had to take a few guesses before I got the string path correct. This is clearer.

**Comment by bryanhelmig** [comment]
The only caveat would be when someone wants to make a custom Zapier app wrapper - they may want their users to be agnostic to the methods _actually_ created behind the scene. They would have to provide their own little tester utility I guess.

**Comment by bryanhelmig** [comment]
To accomplish this we'd need to:
- [ ] remove the references in `zapier describe` https://github.com/zapier/zapier-platform-cli/issues/5
- [ ] prune down `resolve-method-path.js` and accompanying tests
- [ ] mark a breaking change (do we need to add a `CHANGES.md`?)

**Comment by bryanhelmig** [comment]
Closing for PR.
