### ISSUE TITLE
build-boilerplate should happen after npm publish

### ISSUE THREAD

**Issue by eliangcs** [zapier/zapier-platform-core#106]
See https://travis-ci.org/zapier/zapier-platform-core/jobs/405815785#L1608-L1614.

`npm run build-boilerplate` requires the new version of `zapier-platform-core` to be on npm. But currently with our Travis config, `build-boilerplate` runs before we publish `zapier-platform-core` to npm, which leads to a tiny and incorrect boilerplate zip.

`build-boilerplate` should run **after** `npm publish` and **before** the S3 deployment. I looked it up in Travis' [deployment doc](https://docs.travis-ci.com/user/customizing-the-build/). They have `before_deploy` and `after_deploy`. There doesn't seem to be a way to insert a custom command between two deployment providers.

**Comment by eliangcs** [comment]
cc @BrunoBernardino

**Comment by BrunoBernardino** [comment]
Any suggestions @jamescarr ?

**Comment by eliangcs** [comment]
Instead of using the Travis' built-in `s3` provider, I think we can use the [`script`](https://docs.travis-ci.com/user/deployment/script/) provider. In that script, we'll run `npm run build-boilerplate` and upload the boilerplate zip to S3.

**Comment by zapzap** [comment]
This issue has been copied into our private issue (as [PDE-510](https://zapierorg.atlassian.net/rest/api/2/issue/17217)) tracker. Thanks for the report! We'll update this as we learn more.

**Comment by zapzap** [comment]
This issue has been copied into our private issue (as [PDE-511](https://zapierorg.atlassian.net/rest/api/2/issue/17218)) tracker. Thanks for the report! We'll update this as we learn more.
