### ISSUE TITLE
I think we're requiring hook payloads to contain an `id`

### ISSUE THREAD

**Issue by codekirei** [zapier/zapier-platform-core#32]
AFAICT we're doing the trigger has id check on hook trigger data. Is this intentional? Makes sense for polling triggers, but seems odd that we're also running it against hooks.

https://github.com/zapier/zapier-platform-core/blob/master/src/checks/trigger-has-id.js

**Comment by bcooksey** [comment]
Yup, we are requiring that. We have this [shouldRun](https://github.com/zapier/zapier-platform-core/blob/5706ba829d778488f1ddc4762ea6ab9b36ea3f28/src/app-middlewares/after/checks.js#L34), but for the id check, this is simply looking to see [if it's a trigger](https://github.com/zapier/zapier-platform-core/blob/5706ba829d778488f1ddc4762ea6ab9b36ea3f28/src/checks/trigger-has-id.js#L12).

We can discuss if this is a bug or a reasonable constraint.

**Comment by codekirei** [comment]
Cool, thanks for confirming! As for whether it's a reasonable constraint, what was the original inspiration for this check? I imagine we want to make sure polling trigger data includes an `id` for deduplication, but that doesn't apply for hooks.

Is there another reason we're wanting to ensure trigger data contains an `id`? If not, I'd be in favor of restricting this restraint to just polling triggers.

If we do decide to stick with this as-is, we'll probably want to be a bit more explicit about this requirement in our docs &mdash; I'm happy to make the that update if that's the consensus.

**Comment by bryanhelmig** [comment]
> I'd be in favor of restricting this restraint to just polling triggers.

That sounds reasonable!

**Comment by xavdid** [comment]
+1 to just polling triggers to semi-match the v2 setup

**Comment by bcooksey** [comment]
In that case, we can schedule a fix

**Comment by xavdid** [comment]
Sweet. I was going to grab this and #25, since they seem very related

**Comment by jbaranski** [comment]
`resources.*.list.operation.perform` is required to have a field called "id" in the response, but the API I'm working with won't return an "id" field (it's `_id`) -- why is this check even here? 

Maybe I'm doing something wrong but I don't think so. This same check isn't done `resources.*.get.operation.perform` which is even more confusing.

Can I pass some kind of flag or param to specify what the "id" field actually is?

**Comment by jbaranski** [comment]
If I pass `skipChecks: ['triggerHasId']` in the request `bundle` the zapier API skips out of this check. In my plugin I'll have to check if this is the list operation and if so add this skip check in.

If I'm doing it wrong please let me know. Thanks.
