### ISSUE TITLE
File Upload works locally/test but sends hydration URL online

### ISSUE THREAD

**Issue by FokkeZB** [zapier/zapier-platform-core#35]
User reports that file uploads modelled after https://github.com/zapier/zapier-platform-example-app-files work locally when running the tests, but fails online.

I can reproduce this using https://github.com/zapier/zapier-platform-example-app-files and changing the endpoint to a requestbin: https://requestb.in/1bj76zt1?inspect

Local tests produce requests as expected:

![](https://cdn.zapier.com/storage/photos/894fa7f9e232e96aadc71632bf1db3c2.png)

Online (DropBox > Example Upload) it sends the hydration URL instead of the data:

![](https://cdn.zapier.com/storage/photos/84fa38e1f22acf61dd9ea81581ebcd5f.png)

PS: Additionally, the tests for https://github.com/zapier/zapier-platform-example-app-files fail on:

```
  3) hydrators uploadFile should download files:
     only absolute urls are supported
```

**Comment by FokkeZB** [comment]
When I change https://github.com/zapier/zapier-platform-example-app-files/blob/master/creates/uploadFile.js#L9 to `formData.append('file', request(bundle.inputData.file));` it now works online (https://requestb.in/ounha1ou?inspect) but fails local tests: 

```
  creates
    uploadFile
Unhandled error: Error: options.uri is a required argument
```

**Comment by FokkeZB** [comment]
This works both local and online, but it's definitely a workaround and not a great developer experience:

```js
formData.append('file', (typeof bundle.inputData.file === 'object') ? bundle.inputData.file : request(bundle.inputData.file));
```

**Comment by bryanhelmig** [comment]
Instead of just wrapping in a ternary -- why is it failing online instead of the test? If it works in the test, it should work in production.

**Comment by FokkeZB** [comment]
Because local it gets the file data while online it gets the hydration URL.

Fully agree if behaviour should be same both local and online. I'd prefer for it to get the file since if you'd want an URL you'd use a unicode field instead of a file field.

**Comment by bcooksey** [comment]
@FokkeZB ah yea, so [this](https://github.com/zapier/zapier-platform-example-app-files/blob/master/test/creates.js#L15) will never happen in production. We have to pass the dev app a hydrate string, which they can use to fetch the file themselves, then upload to their endpoint.

So looks like we'll need to update the example app to have realistic test scenarios.

**Comment by FokkeZB** [comment]
Ah, right! Then indeed we need to update:

- https://github.com/zapier/zapier-platform-example-app-files/blob/master/test/creates.js to not send file data but file (hydration) URLs
- https://github.com/zapier/zapier-platform-example-app-files/blob/master/creates/uploadFile.js to not expect file data but an URL and make a request to get the data

Am I correct?

**Comment by bcooksey** [comment]
Correct, though I think any URL will do for the tests, doesn't even have to be a proper hydrate URL

**Comment by FokkeZB** [comment]
Tracking in PR:

https://github.com/zapier/zapier-platform-example-app-files/pull/5
