### ISSUE TITLE
Better censoring of ad-hoc sensitive values.

### ISSUE THREAD

**Issue by bryanhelmig** [zapier/zapier-platform-core#4]
For example - if an endpoint returns `{"access_token": "whatever"}` we're not "intelligently" interpreting the JSON and censoring it - we only censor things sent already in `bundle.authData`.

For example - Sentry does intelligent scrubbing in their clients for variable names/configs/etc. ALA https://github.com/getsentry/sentry/blob/8.10.0/src/sentry/constants.py#L166-L175.

**Comment by lvh-zapier** [comment]
Similarly (not sure if this warrants a separate ticket), short strings are not censored: https://github.com/zapier/zapier-platform-core/blob/c06fb327155663d5f2cb6d44562112b18cc2845a/src/tools/create-logger.js#L69-L76

(I'm not sure I understand why, but I haven't really tried to understand the code around it.)

**Comment by bryanhelmig** [comment]
Mostly that is to knock down spamming logs (sometimes a field like `datacenter: a` will result in replacing tons of random `a` strings with needlessly censored values. We're sort of assuming anything shorter than 5 chars is not a proper "secret".

**Comment by lvh-zapier** [comment]
Makes sense. That was my assumption; I'm glad there's no deeper reason I'm missing :)

**Comment by BrunoBernardino** [comment]
The related PR added a test to confirm everything from `bundle.authData` is being censored properly (even inside strings, not just "plain" objects), but the logic of this Feature Request will need to be handled in a separate PR, later (more info in #24).

**Comment by ronniebermejo** [comment]
Wondering if there is any update on censoring ad-hoc response data? thks

**Comment by BrunoBernardino** [comment]
Hi @ronniebermejo, thanks for reaching out!

It's still in the backlog, we're currently prioritizing other more requested features.

We will definitely prioritize this one higher if more people ask for it. Is there a specific set of fields you were looking to auto-censor?

**Comment by wking** [comment]
On Tue, Apr 03, 2018 at 08:50:26AM +0000, Bruno Bernardino wrote:
> We will definitely prioritize this one higher if more people ask for
> it.

Is the best way to do that +1-ing the initial post here?  I've done
that already ;).  @ronniebermejo, on the other hand, went with a bump
comment.  Would it be easier if we consolidated around one approach?
Maybe topic +1s with an additional bump comment if it's been six
months since the last activity?

Also, are there any pointers to public repositories where folks can
chip in on this?  Or is the code for this internal to Zapier?

**Comment by ronniebermejo** [comment]
@BrunoBernardino -> on response: `token`
Would be great if the censored keywords could be configured somewhere.

**Comment by BrunoBernardino** [comment]
@wking both work, really. Your approach with +1 and bump for 6mo of inactivity seems the cleaner.

Also, here is where that is handled (values are censored by `core` before being logged to Zapier): https://github.com/zapier/zapier-platform-core/blob/master/src/tools/create-logger.js#L63-L78

Thanks for the interest! Also @ronniebermejo your idea sounds really good, and a good addition to the original idea in this issue.

**Comment by eliangcs** [comment]
Fixed in #77 and will be shipped with v5.2.0.
