### ISSUE TITLE
Values of children fields defined via Function not nested

### ISSUE THREAD

**Issue by FokkeZB** [zapier/zapier-platform-core#40]
When you define children fields via a function (see CLI app 762) it shows OK in the editor:

![](https://cdn.zapier.com/storage/photos/5f533884cda8049bdeb62ff60305fcd1.png)

But only the values for the static defined children fields are nested:

![](https://cdn.zapier.com/storage/photos/0fd85fdf320f9a18a2b818dee8a87904.png)

And when you map arrays to them the values will be joined by comma:

![](https://cdn.zapier.com/storage/photos/4068b8151c295794e889f9c2ed47fc73.png)

HS: https://secure.helpscout.net/conversation/377971902/554113/?folderId=1139153

**Comment by FokkeZB** [comment]
@zapier/platform

**Comment by BrunoBernardino** [comment]
This is a known limitation on our platform (we only do that parent/child mapping on non-custom fields). We're investigating if/how could we get around that.

**Comment by BrunoBernardino** [comment]
This is currently in the backlog, as it will require much planning.

**Comment by xavdid** [comment]
given that this is a large undertaking and there hasn't been any movement on it, i'm going to mark it as `wontfix`.

**Comment by bcooksey** [comment]
Actually, we forgot to close this out, but any app on platform 8.X+ will have this working as expected!
