### ISSUE TITLE
Some of Lodash's string functions may be consuming a lot of memory on AWS Lambda

### ISSUE THREAD

**Issue by bcooksey** [zapier/zapier-platform-core#53]
## Description

While working on file uploads with a CLI App, we've seen regular errors from Lambda and our function invocations dying. Recently, I enabled logging on one of these functions and found this very brief JS stacktrace:

![](https://cdn.zapier.com/storage/photos/e7d5a287787331b1dc739aa6c7be5e00.png)

That `unicodeToArray` got me curious. Looking at [Lodash source](https://github.com/lodash/lodash/blob/d10b44bdef2b735865c493fbaec8687ec8998aef/.internal/unicodeToArray.js#L38), we see this is indeed running a regular expression on whatever comes into it. Turns out this function is used by `stringToArray`, which is called by lots of Lodash functions in the trim, pad, and truncate realm.

With this bit of a hint, I went hunting and was able to find [this use of truncate](https://github.com/zapier/zapier-platform-core/blob/5fed875579a82f7edc8a56cc7ff014b5503fc098/src/tools/create-logger.js#L12) by our logger.

My theory is this: When a large file like a 25 MB movie gets passed through lambda, our logger is running `_.truncate()` on the raw binary string of data. Underhood, Lodash is running that regular expression on the binary string and it's causing massive amounts of memory usage.

## Replicating

This is the hard part. I had a consistent failure scenario, made a tweak locally to our logger, uploaded it in a test app. Errors went away! Then I reverted the fix and continued to see success, so I'm not positive what's happening anymore.

**Comment by bcooksey** [comment]
Ok, found a way to at least prove that `_.truncate()` is spiking memory usage.

1. Generate a 25 MB file with `dd if=/dev/urandom of=bigfile.dat bs=1048576 count=25`
2. Drop this into `foo.js`

    ```javascript
    const fs = require('fs');
    const _ = require('lodash');

    const data = fs.readFileSync('bigfile.dat');
    console.log(process.memoryUsage());
    _.truncate(data, {length: 3500, omission: '[...]'});
    console.log(process.memoryUsage());
    ```
1. `node foo.js`

I was seeing spikes in the 900-1000 MB range for rss, heapTotal, and heapUsed:

```
{ rss: 53846016,
  heapTotal: 12718080,
  heapUsed: 6912384,
  external: 26222780 }
{ rss: 985133056,
  heapTotal: 941199360,
  heapUsed: 907690560,
  external: 26222780 }
```

**Comment by bcooksey** [comment]
cc @BrunoBernardino as this may get worse now that we do the patch and record logs from libs besides `z.request()`. Anybody who upgrades and is transferring moderately sized payloads may get bit by this.

**Comment by BrunoBernardino** [comment]
That's a great catch! Indeed we should change that to something less cool but easier on the used memory like `.substr()`.
